import {
  AuditLog,
  EmailLog,
  JobChannelPublishTrack,
  JobPosting,
  RecruitmentChannel,
  RecruitmentTimelineEvent,
  User,
} from '../types'

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Nhật Trần',
    email: 'nhat.tran@thdcyber.vn',
    role: 'HR Recruiter',
    department: 'IT',
    avatar: 'NT',
  },
  {
    id: 'usr-2',
    name: 'Lan Nguyễn',
    email: 'lan.nguyen@thdcyber.vn',
    role: 'HR Manager',
    department: 'HR',
    avatar: 'LN',
  },
  {
    id: 'usr-3',
    name: 'Minh Vũ',
    email: 'minh.vu@thdcyber.vn',
    role: 'TA Lead',
    department: 'IT',
    avatar: 'MV',
  },
  {
    id: 'usr-4',
    name: 'Admin THD',
    email: 'admin@thdcyber.vn',
    role: 'Admin',
    department: 'Management',
    avatar: 'AD',
  },
]

export const INITIAL_CHANNELS: RecruitmentChannel[] = [
  {
    id: 'chn-linkedin',
    name: 'LinkedIn',
    category: 'Social Media',
    activeJobsCount: 15,
    totalCandidates: 250,
    trend: '+18%',
    status: 'Active',
  },
  {
    id: 'chn-topcv',
    name: 'TopCV',
    category: 'Job Board',
    activeJobsCount: 12,
    totalCandidates: 135,
    trend: '+11%',
    status: 'Active',
  },
  {
    id: 'chn-facebook',
    name: 'Facebook / MXH',
    category: 'Social Media',
    activeJobsCount: 8,
    totalCandidates: 96,
    trend: '+6%',
    status: 'Active',
  },
  {
    id: 'chn-vietnamworks',
    name: 'VietnamWorks',
    category: 'Job Board',
    activeJobsCount: 7,
    totalCandidates: 88,
    trend: '+4%',
    status: 'Active',
  },
  {
    id: 'chn-website',
    name: 'Company Website',
    category: 'Company Website',
    activeJobsCount: 24,
    totalCandidates: 62,
    trend: '+12%',
    status: 'Active',
  },
  {
    id: 'chn-referral',
    name: 'Giới thiệu nội bộ (Referral)',
    category: 'Employee Referral',
    activeJobsCount: 6,
    totalCandidates: 45,
    trend: '+9%',
    status: 'Active',
  },
]

export const INITIAL_JOBS: JobPosting[] = [
  {
    id: 'job-1',
    title: 'Backend Developer (Kỹ sư Backend)',
    department: 'IT',
    location: 'TP. Hồ Chí Minh',
    status: 'Published',
    description:
      'Chịu trách nhiệm thiết kế, xây dựng và tối ưu hóa các dịch vụ phía máy chủ (Backend Services) và RESTful APIs cho hệ thống của công ty.',
    experience: 'Từ 3 năm kinh nghiệm lập trình Backend (Node.js, Python hoặc Java).',
    skills: 'Thành thạo SQL/NoSQL, RESTful API, Docker/Kubernetes, Microservices.',
    english: 'Đọc hiểu tài liệu chuyên ngành tốt, giao tiếp cơ bản.',
    education: 'Cử nhân Công nghệ Thông tin hoặc chuyên ngành liên quan.',
    note: 'Ưu tiên ứng viên có kiến thức về bảo mật thông tin và Cloud AWS/Azure.',
    recruiterId: 'usr-1',
    recruiterName: 'Nhật Trần',
    applicantsCount: 48,
    createdDate: '2026-07-01',
    updatedDate: '2026-07-15',
    expiryDate: '2026-08-15',
    type: 'Full-time',
    publishedChannels: ['chn-linkedin', 'chn-topcv', 'chn-website'],
    timelineEvents: [
      { id: 't1', jobId: 'job-1', date: '2026-07-01 09:00', action: 'Created', actor: 'Nhật Trần', note: 'Tạo phác thảo bản nháp' },
      { id: 't2', jobId: 'job-1', date: '2026-07-02 14:30', action: 'Approved', actor: 'Lan Nguyễn', note: 'Phê duyệt yêu cầu tuyển dụng' },
      { id: 't3', jobId: 'job-1', date: '2026-07-03 10:15', action: 'Published', actor: 'Nhật Trần', note: 'Xuất bản lên LinkedIn & TopCV' },
      { id: 't4', jobId: 'job-1', date: '2026-07-15 16:00', action: 'Updated', actor: 'Nhật Trần', note: 'Bổ sung tiêu chí Cloud AWS' },
    ],
  },
  {
    id: 'job-2',
    title: 'Business Analyst (PT Nghiệp vụ)',
    department: 'IT',
    location: 'Hà Nội',
    status: 'Published',
    description:
      'Thu thập, phân tích yêu cầu nghiệp vụ từ khách hàng và các bên liên quan, viết tài liệu BRD/SRS cho đội phát triển phần mềm.',
    experience: '3+ năm kinh nghiệm BA phần mềm hoặc tư vấn giải pháp IT.',
    skills: 'UML, BPMN, SQL cơ bản, kỹ năng giao tiếp và truyền đạt xuất sắc.',
    english: 'Tiếng Anh giao tiếp và viết tài liệu thành thạo.',
    education: 'Đại học chuyên ngành CNTT, Hệ thống thông tin quản lý hoặc Quản trị kinh doanh.',
    recruiterId: 'usr-3',
    recruiterName: 'Minh Vũ',
    applicantsCount: 29,
    createdDate: '2026-07-05',
    updatedDate: '2026-07-18',
    expiryDate: '2026-08-20',
    type: 'Full-time',
    publishedChannels: ['chn-linkedin', 'chn-website'],
    timelineEvents: [
      { id: 't5', jobId: 'job-2', date: '2026-07-05 10:00', action: 'Created', actor: 'Minh Vũ', note: 'Tạo tin bài BA' },
      { id: 't6', jobId: 'job-2', date: '2026-07-06 11:20', action: 'Published', actor: 'Minh Vũ', note: 'Đăng tuyển Website Công ty & LinkedIn' },
    ],
  },
  {
    id: 'job-3',
    title: 'HR Executive (Chuyên viên Nhân sự)',
    department: 'HR',
    location: 'TP. Hồ Chí Minh',
    status: 'Pending Approval',
    description:
      'Hỗ trợ công tác tuyển dụng, tiếp nhận nhân sự mới, tổ chức truyền thông nội bộ và phối hợp quản lý hồ sơ nhân sự.',
    experience: '1-2 năm kinh nghiệm ở vị trí HR Generalist/Recruiter.',
    skills: 'Giao tiếp tốt, sử dụng thành thạo MS Office, tinh thần trách nhiệm cao.',
    english: 'Giao tiếp cơ bản.',
    education: 'Đại học chuyên ngành Quản trị Nhân sự, Luật hoặc Ngoại ngữ.',
    recruiterId: 'usr-2',
    recruiterName: 'Lan Nguyễn',
    applicantsCount: 19,
    createdDate: '2026-07-20',
    updatedDate: '2026-07-20',
    expiryDate: '2026-08-30',
    type: 'Full-time',
    publishedChannels: [],
    timelineEvents: [
      { id: 't7', jobId: 'job-3', date: '2026-07-20 15:00', action: 'Submitted Approval', actor: 'Lan Nguyễn', note: 'Gửi đề xuất tuyển dụng chờ duyệt' },
    ],
  },
  {
    id: 'job-4',
    title: 'Digital Marketing Lead',
    department: 'Marketing',
    location: 'Đà Nẵng',
    status: 'Draft',
    description:
      'Xây dựng chiến lược Marketing tổng thể trên các kênh kỹ thuật số nhằm gia tăng nhận diện thương hiệu và tìm kiếm khách hàng tiềm năng.',
    experience: '4+ năm kinh nghiệm trong lĩnh vực Digital Marketing.',
    skills: 'SEO, SEM, Facebook Ads, Google Analytics, Content Strategy.',
    english: 'Lưu khoát 4 kỹ năng.',
    recruiterId: 'usr-1',
    recruiterName: 'Nhật Trần',
    applicantsCount: 8,
    createdDate: '2026-07-22',
    updatedDate: '2026-07-22',
    type: 'Contract',
    publishedChannels: [],
  },
  {
    id: 'job-5',
    title: 'Senior Security Specialist',
    department: 'IT',
    location: 'TP. Hồ Chí Minh',
    status: 'Paused',
    description:
      'Thực hiện đánh giá an toàn thông tin, rà soát lỗ hổng bảo mật ứng dụng và hạ tầng mạng cho doanh nghiệp.',
    experience: '5+ năm kinh nghiệm trong ngành Security/Pentest.',
    skills: 'OSCP, CISSP, CEH, thành thạo Pentesting & SOC analysis.',
    recruiterId: 'usr-3',
    recruiterName: 'Minh Vũ',
    applicantsCount: 14,
    createdDate: '2026-06-10',
    updatedDate: '2026-07-10',
    expiryDate: '2026-07-31',
    type: 'Full-time',
    publishedChannels: ['chn-linkedin'],
  },
]

export const INITIAL_PUBLISH_TRACKS: JobChannelPublishTrack[] = [
  {
    jobId: 'job-1',
    channelId: 'chn-linkedin',
    status: 'Published',
    publishedDate: '2026-07-03',
    postUrl: 'https://linkedin.com/jobs/view/123456',
  },
  {
    jobId: 'job-1',
    channelId: 'chn-topcv',
    status: 'Published',
    publishedDate: '2026-07-03',
    postUrl: 'https://topcv.vn/brand/thdcyber/backend-dev',
  },
  {
    jobId: 'job-1',
    channelId: 'chn-facebook',
    status: 'Draft',
  },
  {
    jobId: 'job-1',
    channelId: 'chn-website',
    status: 'Published',
    publishedDate: '2026-07-02',
    postUrl: 'https://thdcyber.vn/careers/backend-dev',
  },
  {
    jobId: 'job-2',
    channelId: 'chn-linkedin',
    status: 'Published',
    publishedDate: '2026-07-06',
  },
  {
    jobId: 'job-2',
    channelId: 'chn-facebook',
    status: 'Draft',
  },
  {
    jobId: 'job-2',
    channelId: 'chn-website',
    status: 'Published',
    publishedDate: '2026-07-05',
  },
]

export const INITIAL_TIMELINE: RecruitmentTimelineEvent[] = [
  {
    id: 'tl-1',
    jobId: 'job-1',
    date: '2026-07-01 09:00',
    action: 'Created',
    actor: 'Nhật Trần',
    note: 'Tạo bản nháp vị trí Kỹ sư Backend',
  },
  {
    id: 'tl-2',
    jobId: 'job-1',
    date: '2026-07-02 14:30',
    action: 'Approved',
    actor: 'Lan Nguyễn',
    note: 'Đã duyệt yêu cầu tuyển dụng',
  },
  {
    id: 'tl-3',
    jobId: 'job-1',
    date: '2026-07-03 10:15',
    action: 'Published',
    actor: 'Nhật Trần',
    note: 'Đã xuất bản lên LinkedIn & TopCV',
  },
  {
    id: 'tl-4',
    jobId: 'job-1',
    date: '2026-07-15 16:00',
    action: 'Updated',
    actor: 'Nhật Trần',
    note: 'Cập nhật bổ sung yêu cầu Cloud AWS',
  },
]

export const INITIAL_EMAILS: EmailLog[] = [
  {
    id: 'em-1',
    jobId: 'job-1',
    jobTitle: 'Backend Developer',
    sender: 'Nhật Trần',
    recipient: 'Phong Trần',
    recipientEmail: 'phong.tran@gmail.com',
    topic: 'Xác nhận lịch phỏng vấn vị trí Backend Developer',
    content: 'Chào Phong, HR xin gửi lời mời phỏng vấn vòng 1 vào lúc 14h00 ngày 30/07/2026...',
    time: '10 phút trước',
    status: 'Sent',
  },
  {
    id: 'em-2',
    jobId: 'job-3',
    jobTitle: 'HR Executive',
    sender: 'Lan Nguyễn',
    recipient: 'HR Ops',
    recipientEmail: 'hrops@thdcyber.vn',
    topic: 'Yêu cầu phê duyệt đề xuất vị trí HR Executive',
    content: 'Kính gửi chị Lan, em vừa gửi đề xuất tuyển HR Executive, nhờ chị xem xét...',
    time: '35 phút trước',
    status: 'Replied',
  },
  {
    id: 'em-3',
    jobId: 'job-1',
    jobTitle: 'Backend Developer',
    sender: 'Recruiter Team',
    recipient: 'TopCV Support',
    recipientEmail: 'support@topcv.vn',
    topic: 'Yêu cầu làm mới tin tuyển dụng chiến dịch Tháng 7',
    content: 'Nhờ TopCV hỗ trợ đẩy tin vị trí Backend Developer...',
    time: '2 giờ trước',
    status: 'Delivered',
  },
]

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    timestamp: '2026-07-28 08:30:12',
    userId: 'usr-1',
    userName: 'Nhật Trần',
    action: 'Login',
    details: 'Đăng nhập hệ thống từ IP 118.69.182.10',
  },
  {
    id: 'log-2',
    timestamp: '2026-07-28 08:35:44',
    userId: 'usr-1',
    userName: 'Nhật Trần',
    action: 'Publish Job',
    details: 'Đăng tuyển bài viết Backend Developer lên kênh LinkedIn',
  },
  {
    id: 'log-3',
    timestamp: '2026-07-28 08:40:00',
    userId: 'usr-2',
    userName: 'Lan Nguyễn',
    action: 'Send Email',
    details: 'Gửi email xác nhận tới ứng viên Phong Trần',
  },
]
